using Microsoft.CodeAnalysis;
using System;
using System.Reflection;

namespace MintPlayer.AspNetCore.SpaServices.Generators
{
	[Generator]
	public class SpaRoutesSourceGenerator : ISourceGenerator
	{
		public void Initialize(GeneratorInitializationContext context)
		{
			
		}

		public void Execute(GeneratorExecutionContext context)
		{
			// Find the main method
			var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

			// Build up the source code
			string source = $@"// <auto-generated/>
using System;

namespace {mainMethod.ContainingNamespace.ToDisplayString()}
{{
    public static class Test
    {{
        public static void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from '{{name}}'"");
    }}
}}
";
			var typeName = mainMethod.ContainingType.Name;

			// Add the source code to the compilation
			context.AddSource($"{typeName}.g.cs", source);
		}
	}
}
