<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<LangVersion>15</LangVersion>
		<PublishAot>true</PublishAot>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
</Project>
